#!/usr/bin/env python
"""Generate report tables from SORA Academic thesis output."""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd
from pandas.errors import EmptyDataError

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_DIR = ROOT / "thesis_output_academic"


def load_summary(output_dir: Path) -> pd.DataFrame:
    """Load the academic summary report."""
    summary_path = output_dir / "summary_report.csv"
    if not summary_path.exists():
        raise FileNotFoundError(f"No summary report found at {summary_path}")
    try:
        summary_df = pd.read_csv(summary_path)
    except EmptyDataError as exc:
        raise ValueError(f"Summary report is empty: {summary_path}") from exc
    required_columns = {"subject", "avg_fitness", "days", "optimized_days"}
    missing = required_columns - set(summary_df.columns)
    if missing:
        raise ValueError(f"Summary report missing columns: {sorted(missing)}")
    if summary_df.empty:
        raise ValueError(f"Summary report has no rows: {summary_path}")
    return summary_df


def write_markdown(summary_df: pd.DataFrame, output_path: Path) -> None:
    """Write a markdown report."""
    markdown_table = summary_df.to_markdown(index=False)
    content = "\n".join(
        [
            "# SORA Academic Results Summary",
            "",
            "## Weekly Optimization Metrics",
            "",
            markdown_table,
            "",
            "## Statistics",
            "",
            f"- Subjects tested: {len(summary_df)}",
            f"- Average fitness: {summary_df['avg_fitness'].mean():.4f}",
            f"- Best average fitness: {summary_df['avg_fitness'].max():.4f}",
            f"- Optimized days: {int(summary_df['optimized_days'].sum())}/{int(summary_df['days'].sum())}",
            "",
            "Generated by SORA Academic.",
        ]
    )
    output_path.write_text(content, encoding="utf-8")


def write_latex(summary_df: pd.DataFrame, output_path: Path) -> None:
    """Write a standalone LaTeX table."""
    latex_table = summary_df.to_latex(index=False, float_format=lambda value: f"{value:.4f}")
    output_path.write_text(
        f"""\
\\documentclass{{article}}
\\usepackage{{booktabs}}
\\begin{{document}}
\\begin{{table}}[h]
\\centering
\\caption{{SORA Academic Weekly Optimization Results}}
\\label{{tab:sora-academic-results}}
{latex_table}
\\end{{table}}
\\end{{document}}
""",
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate SORA Academic report tables")
    parser.add_argument("--format", choices=["csv", "markdown", "latex", "all"], default="markdown")
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    args = parser.parse_args()

    try:
        summary_df = load_summary(args.output_dir)
    except (FileNotFoundError, ValueError) as exc:
        print(f"[ERROR] {exc}")
        return 1
    if args.format in {"csv", "all"}:
        summary_df.to_csv(args.output_dir / "REPORT.csv", index=False)
    if args.format in {"markdown", "all"}:
        write_markdown(summary_df, args.output_dir / "REPORT.md")
    if args.format in {"latex", "all"}:
        write_latex(summary_df, args.output_dir / "REPORT.tex")

    print(f"[OK] Report generated in {args.output_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
